// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");

function point(face) {
  if (face !== 1) {
    if (face !== 0) {
      return 10;
    } else {
      return 11;
    }
  } else {
    return 2;
  }
}

var Face = {
  point: point
};

function point$1(card) {
  if (card[0] !== 0) {
    return point(card[1]);
  } else {
    return (point(card[1]) << 1);
  }
}

var Card = {
  point: point$1
};

function value(count) {
  return count[0];
}

function create(count) {
  if (count >= 0) {
    return /* Ok */Block.__(0, [/* CardCount */[count]]);
  } else {
    return /* Error */Block.__(1, ["Invalid Count"]);
  }
}

var CardCount = {
  value: value,
  create: create
};

function newGame(param) {
  
}

var BlackJack = {
  newGame: newGame
};

var PlayingCard = {
  Face: Face,
  Card: Card,
  CardCount: CardCount,
  BlackJack: BlackJack
};

exports.PlayingCard = PlayingCard;
/* No side effect */
